### ISSUE TITLE
Simplify installation

### ISSUE THREAD

**Issue by cool-RR** [wapringle/mockbrython#2]
Any reason this shouldn't be pip-installable? I just copied it into `site-packages` instead of the complicated installation instructions.

**Comment by wapringle** [comment]
I would prefer to have it a bit more stable, before packaging it.

**Comment by cool-RR** [comment]
Keep in mind that if it was packaged, it would be easier for me to upgrade and see your new additions. Now it's a chore.

**Comment by cool-RR** [comment]
You can package it with a version of 0.0.1, which sends the message of "Don't expect any kind of stability from this package."

**Comment by wapringle** [comment]
Hi

Should have your list cleared apart from this issue. I will give it a go
and see how it works out..

Thanks for your useful feedback and I will keep you posted.

regards

Bill Pringle

**Comment by wapringle** [comment]
Just to let you know I have published mockbrython on PyPI as you suggested. You can have a sneak preview before I do a formal announcement in the next few days.

I have extended the package to cover all the Brython calls documented, with function prototypes and dummies for IDEs - generally more complete than the first version

Hope you like it.

$ pip install mockbrython

Enjoy

**Comment by cool-RR** [comment]
Cool, works great! Thank you.
